### ISSUE TITLE
perf: getting args

### ISSUE THREAD

**Issue by m-muecke** [tidyfun/tf#111]
in a few places there is the following pattern:

```r
tf::tf_arg(x) |>
  unlist(use.names = FALSE) |>
  unique() |>
  sort()
```

I believe only irregular data requires this treatment, since args for regular data should always be an unique numeric vector.
Since this operation is quite expensive, we could factor out this pattern:

```r
get_args <- function(x) {
  args <- tf::tf_arg(x)
  if (tf::is_irreg(x) {
    args |> unlist(use.names = FALSE) |> unique() |> sort()
  }
  args
}

**Comment by fabian-s** [comment]
true --  maybe call it `get_args_vector` instead of `get_args`?
