### ISSUE TITLE
use checkmate/rlang for arg choice?

### ISSUE THREAD

**Issue by m-muecke** [tidyfun/tf#122]
Something very subjective, nevertheless wanted to get it documented. Since, we're currently using checkmate one could use `checkmate::check_choice()` for checking string options, instead of `match.arg()`. This does not really make a performance difference and is just a style/pattern choice. There is also the rlang alternative with a normal and more bare-bones version for performance. Both checkmate and rlang have the advantage of not allowing partial matching.

``` r
fn1 <- function(basis = c("spline", "fpc", "wavelet")) {
  basis <- match.arg(basis)
  basis
}

fn2 <- function(basis = "spline") {
  checkmate::check_choice(basis, c("spline", "fpc", "wavelet"))
  basis
}

fn3 <- function(basis = c("spline", "fpc", "wavelet")) {
  basis <- rlang::arg_match(basis)
  basis
}

fn4 <- function(basis = "spline") {
  basis <- rlang::arg_match0(basis, c("spline", "fpc", "wavelet"))
  basis
}

bench::mark(fn1(), fn2(), fn3(), fn4())
#> # A tibble: 4 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 fn1()        2.25µs   2.54µs   280705.        0B     56.2
#> 2 fn2()         3.2µs   3.44µs   267779.     285KB     53.6
#> 3 fn3()        39.4µs  42.56µs    22724.     208KB     43.3
#> 4 fn4()      778.99ns 861.01ns   998494.        0B      0
```

<sup>Created on 2024-08-29 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by fabian-s** [comment]
thanks, but I think `match.arg` is fine.
