### ISSUE TITLE
functionality for applying a given basis to new data

### ISSUE THREAD

**Issue by fabian-s** [tidyfun/tf#3]
- [x] `tfb_fpc`:
     - ... difficult to do exactly -- score computation depends on internals of `method` (do PACE or simple ridge estimate or just LS etc)
- [x] `tfb_spline` 
     - ... easy for unpenalized fits
     - terrible otherwise -- use same `sp`, fitting args etc. probably need to preserve more of that in `tfb` objects
- ~~`tfb_wavelet`~~

**Comment by fabian-s** [comment]
common operation that should be easy:  apply given FPC (or spline!) basis to NEW data

**Comment by jeff-goldsmith** [comment]
seems like a general `tfb` class that takes a known "basis representation" (including things like tuning parameters) and a corresponding method for estimating coefficients would work. this would work for splines and FPCA-based methods, as long as everything for the coefficient estimation was included in the "basis representation". 

there's probably a way for this to go along with the second bullet, although i dunno that we'd want to require that *every* coefficient estimating approach boil down to mgcv. 

one way to make this concrete is to use something like
```
tfb_vec = tfb(tfd_vec, basis_object)
```
(which assumes that `basis_object` implies a coefficient estimating function). 

a problem is that right now we use `tfb` to do spline smoothing when called directly; that creates an implicit basis object, which stays invisible to users -- but we'd be asking users to know it's explicit when applying the basis representation to new data.

two options:

* write a method that extracts the basis object from a `tfb` vector created by `tfb()`
* separate an initial smoothing from using a known basis representation on new data (e.g. keep `tfb()` as-is and add `tfb_known_rep()` or something with a less stupid name. 
  * (could we repurpose `tf_smooth()` to do what `tfb()` does now, and use `tfb()` for the new case? or is that just worse all around)?

**Comment by fabian-s** [comment]
- every tfb needs "basis set up" and "coefficient finding"
- some basis set up functions will also return penalty params etc for the coef finding (FPCA) some won't.  
in some cases, "basis set up" and "coeff finding" will be iterative (at least when called the first time for new data)
- coefficient functions *can* get  penalty params etc as inputs, but don't have to. difficulty here: calling coef fitting function the 2nd time to reapply same method to new data will need penalty params from first fit.
--> try to define very general tfb constructor that just takes these two functions as inputs. users responsible that the 2 mesh. (terrible UX, but high flex)
--> define `tfb_spline` and `tfb_fpc` constructors with lots of guard rails and easy-to-understand arguments (like we have now)  

**can we then do away with tfb_spline, tfb_fpc subclasses?**

start with tf_rebase.tfb_spline to see how bad this is going to get.

**Comment by fabian-s** [comment]
implement this in `tf_rebase(object, basis_from) `: see 3-tfb-basistransfer branch

- [ ] tfd, tfb_spline: 
- [ ] tfd, tfb_fpc
- [ ] tfb_spline, tfd
- [ ] tfb_fpc, tfd
- [ ] tfb_spline, tfb_fpc 
- [ ] tfb_spline, tfb_fpc 

- [ ] replace/use in (which) vec_cast methods? (makes c()-much more tolerant)
- [ ] use to make Ops more type-tolerant? (at least: for tfd_irreg!) see #5, #10  

learned:

- tfb_fpc will need refactoring based on proper FPCA implementations. FPCA implementations need predict methods. workaround right now is too messy and hard to maintain
-

**Comment by fabian-s** [comment]
@jeff-goldsmith 
if you have time, would appreciate your thoughts on this new feature `tf_rebase` (see test-rebase.R for some examples). 
does this cover what we need for practical applications / what's missing? 
is the documentation clear enough?

**Comment by jeff-goldsmith** [comment]
this is awesome! `tf_rebase` worked like a charm and the help file is clear. Maybe we should add a (possibly contrived) example to the conversion vignette -- something like processing `DTI$cca` separately for `male` and `female` participants, then combining in various ways using `tf_rebase`?
