### ISSUE TITLE
Add (synchronous) covariance / correlation 

### ISSUE THREAD

**Issue by fabian-s** [tidyfun/tf#30]
So: $Cov(y(t), x(t))$ for x, y on same domain.

More general  $Cov(y(t), x(t'))$ (same domain) or $Cov(y(t), x(s))$  (different domains) would need multivariate functions/surfaces.

**Comment by sebffischer** [comment]
I think for the {mlr3fda} project, a different type of correlation was meant, i.e. the correlation of two functions on the individual level.

**Comment by fabian-s** [comment]
OK, so $c(x_i, y_i) = \int_T (x_i(t) -  \bar{x_i})(y_i(t)-\bar{y_i}) dt$
where $\bar{z_i} = |T|^{-1} \int_T z_i(t) dt$ ?

**Comment by sebffischer** [comment]
Also other individual-level operators functions like the minimum / maximum / variance of the functions would be great to have to be able to extract tabular features from these functions.
