### ISSUE TITLE
Signal an error, warning, or message

### ISSUE THREAD

**Issue by m-muecke** [tidyfun/tf#70]
Currently `rlang` is already used in the package, thus I would vote for either using `rlang::abort`, etc. instead of stop and warning for nicer errors or not displaying the call with `stop(call. = FALSE)` and `warning(call. = FALSE)` https://design.tidyverse.org/err-call.html.

Example for using it with stop in the lintr package: https://github.com/r-lib/lintr/blob/main/R/comments.R#L87

**Comment by fabian-s** [comment]
:+1:

**Comment by m-muecke** [comment]
> 👍

whats your preference?

**Comment by fabian-s** [comment]
we can/should move to exception handling with rlang functions, seems standard for tidyverse packages. 
thank you for pointing that out!

**Comment by fabian-s** [comment]
on 2nd thought: 
we use checkmate everywhere and checkmate does not use rlang exceptions anyway, so let's stick with `stop(call. = FALSE)` and `warning(call. = FALSE)`

**Comment by m-muecke** [comment]
> on 2nd thought: we use checkmate everywhere and checkmate does not use rlang exceptions anyway, so let's stick with `stop(call. = FALSE)` and `warning(call. = FALSE)`

Sounds good. With `rlang::abort` you would have to add the environment for all errors in the helper functions anyways, leading to quite a bit of modification. This would've been the pattern in non exported functions:

```r
foo <- function(..., error_call = caller_env()) {
  abort("error", call = error_call)
}
```
