### ISSUE TITLE
Duplicate imports

### ISSUE THREAD

**Issue by m-muecke** [tidyfun/tf#94]
Nitpicking, but there are duplicate package imports for purrr https://github.com/tidyfun/tf/blob/dev/R/tfd-class.R#L1 and https://github.com/tidyfun/tf/blob/dev/R/tfd-class.R#L1 while also import the functions https://github.com/tidyfun/tf/blob/dev/R/fwise.R#L17and using it with the explicit namespace: https://github.com/tidyfun/tf/blob/dev/R/fwise.R#L51 the same is true for the mgcv and stats imports.

Suggestion would be to move the whole package imports (i.e. `@import purrr` to the R/tf-package.R file like done in dplyr or other many other packages: https://github.com/tidyverse/dplyr/blob/main/R/dplyr.R#L6

**Comment by fabian-s** [comment]
true. please go ahead with this if you have the time/energy. 

- the explicit `pkg::function` syntax is no longer prefered, is it?
- i *would* actually prefer to not import whole packages unless we use > 10 functions from it. could adapt the strategy here (https://stackoverflow.com/questions/28513444/how-to-tell-what-packages-you-have-used-in-r) to find&fix all the import sloppiness

**Comment by m-muecke** [comment]
> true. please go ahead with this if you have the time/energy.
> 
> * the explicit `pkg::function` syntax is no longer prefered, is it?
> * i _would_ actually prefer to not import whole packages unless we use > 10 functions from it. could adapt the strategy here (https://stackoverflow.com/questions/28513444/how-to-tell-what-packages-you-have-used-in-r) to find&fix all the import sloppiness

- Ditto, think the n > 10 is good rule of thumb
- Using the namespace prefix, i.e. `pkg:fn` is still common for some packages, where either not a lot of functions are getting used or some semantics or style guide. For example the `cli` package seems to be used in all tidyverse packages with the namespace prefix, see for reference in the purrr package: https://github.com/tidyverse/purrr/blob/d9ae2359ebb7f8efbc5215e8a35e9721e34608eb/R/rate.R#L93, while rlang, vctrs are less common with namespace prefix. And of course use namespace prefix when having the package in suggests. Otherwise it seems to come down to preference with a more dominant convention of import functions/packages
